import fs from 'node:fs';
import path from 'node:path';
import type { ResolvedConfig } from './types.js';

/**
 * CLAUDE.md policy-block drop-in writer.
 *
 * Same ownership split as the tmux drop-in (see tmux-config-manager.ts): the
 * toolkit never edits the user's hand-written, version-controlled
 * ~/.claude/CLAUDE.md. Instead each module that contributes a policy block gets
 * its own generated drop-in file:
 *   {{install_dir}}/claude-md/<moduleId>-<sectionId>.md
 *
 * Unlike tmux (which globs `*.conf` via source-file), CLAUDE.md's `@import`
 * supports `@~/path` but NOT globs — so the user references each drop-in by a
 * stable, fixed path with one @import line they add once (version-controlled):
 *   @~/.config/claude-toolkit/claude-md/auto-dev-github-sync.md
 *
 * Because the import targets a fixed path, the block auto-loads in every session
 * with no manual `cat`/sync step. Install (re)writes the drop-in; uninstall
 * deletes it. Idempotent by construction.
 *
 * The caller (InstallProgress, via buildVarMap) must have already resolved any
 * template vars in `body`.
 */

function dropinPath(config: ResolvedConfig, moduleId: string, sectionId: string): string {
  return path.join(config.claudeMdDir, `${moduleId}-${sectionId}.md`);
}

/** The stable @import line the user adds once to ~/.claude/CLAUDE.md for this block. */
export function claudeMdImportLine(config: ResolvedConfig, moduleId: string, sectionId: string): string {
  return `@${dropinPath(config, moduleId, sectionId)}`;
}

/** Write a module's CLAUDE.md drop-in. `body` must already be template-resolved. */
export function applyClaudeMdBlock(
  config: ResolvedConfig,
  moduleId: string,
  sectionId: string,
  body: string,
): void {
  const header = [
    `<!-- Generated by claude-toolkit (module: ${moduleId}, block: ${sectionId}). DO NOT EDIT. -->`,
    `<!-- Source of truth: src/modules/${moduleId}/manifest.ts (claudeMdBlocks). -->`,
    `<!-- Regenerated on every install; deleted on uninstall. Loaded into the -->`,
    `<!-- user-level CLAUDE.md via the @import line the main file adds once. -->`,
    '',
    '',
  ].join('\n');

  const target = dropinPath(config, moduleId, sectionId);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  const tmp = target + '.tmp';
  fs.writeFileSync(tmp, header + body.trimEnd() + '\n');
  fs.renameSync(tmp, target);
}

/** Delete a module's CLAUDE.md drop-in. */
export function removeClaudeMdBlock(
  config: ResolvedConfig,
  moduleId: string,
  sectionId: string,
): void {
  const target = dropinPath(config, moduleId, sectionId);
  if (fs.existsSync(target)) fs.unlinkSync(target);
}
