import fs from 'node:fs';
import path from 'node:path';
import type { ResolvedConfig } from './types.js';

/**
 * CLAUDE.md policy-block drop-in writer.
 *
 * Same ownership split as the tmux drop-in (see tmux-config-manager.ts): the
 * toolkit never edits the user's hand-written, version-controlled
 * ~/.claude/CLAUDE.md. Instead each module that contributes a policy block gets
 * its own generated drop-in file:
 *   {{install_dir}}/claude-md/<moduleId>-<sectionId>.md
 *
 * Unlike tmux (which globs `*.conf` via source-file), CLAUDE.md's `@import`
 * supports `@~/path` but NOT globs — so the user references each drop-in by a
 * stable, fixed path with one @import line they add once (version-controlled):
 *   @~/.config/claude-toolkit/claude-md/auto-dev-github-sync.md
 *
 * Because the import targets a fixed path, the block auto-loads in every session
 * with no manual `cat`/sync step. Install (re)writes the drop-in; uninstall
 * deletes it. Idempotent by construction.
 *
 * The caller (InstallProgress, via buildVarMap) must have already resolved any
 * template vars in `body`.
 */

function dropinPath(config: ResolvedConfig, moduleId: string, sectionId: string): string {
  return path.join(config.claudeMdDir, `${moduleId}-${sectionId}.md`);
}

/** The stable @import line the user adds once to ~/.claude/CLAUDE.md for this block. */
export function claudeMdImportLine(config: ResolvedConfig, moduleId: string, sectionId: string): string {
  return `@${dropinPath(config, moduleId, sectionId)}`;
}

/** Write a module's CLAUDE.md drop-in. `body` must already be template-resolved. */
export function applyClaudeMdBlock(
  config: ResolvedConfig,
  moduleId: string,
  sectionId: string,
  body: string,
): void {
  const header = [
    `<!-- Generated by claude-toolkit (module: ${moduleId}, block: ${sectionId}). DO NOT EDIT. -->`,
    `<!-- Source of truth: src/modules/${moduleId}/manifest.ts (claudeMdBlocks). -->`,
    `<!-- Regenerated on every install; deleted on uninstall. Loaded into the -->`,
    `<!-- user-level CLAUDE.md via the @import line the main file adds once. -->`,
    '',
    '',
  ].join('\n');

  const target = dropinPath(config, moduleId, sectionId);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  const tmp = target + '.tmp';
  fs.writeFileSync(tmp, header + body.trimEnd() + '\n');
  fs.renameSync(tmp, target);
}

/** Delete a module's CLAUDE.md drop-in. */
export function removeClaudeMdBlock(
  config: ResolvedConfig,
  moduleId: string,
  sectionId: string,
): void {
  const target = dropinPath(config, moduleId, sectionId);
  if (fs.existsSync(target)) fs.unlinkSync(target);
}

/**
 * The canonical user-level CLAUDE.md the toolkit augments. Per the Claude Code
 * docs the documented user memory path is ~/.claude/CLAUDE.md (NOT ~/CLAUDE.md,
 * which is legacy/undocumented). We target the documented path so the import is
 * future-proof.
 */
function userClaudeMdPath(config: ResolvedConfig): string {
  return path.join(config.claudeDir, 'CLAUDE.md');
}

const MARK_PREFIX = '<!-- claude-toolkit:';

function markerComment(moduleId: string, sectionId: string): string {
  return `${MARK_PREFIX}${moduleId}-${sectionId} (managed) -->`;
}

/**
 * Ensure the canonical ~/.claude/CLAUDE.md @imports a module's drop-in, with the
 * minimal, automated invasiveness the policy allows:
 *  - MARKED: each managed line is preceded by a unique marker comment, so we touch
 *    only our own lines, never the user's.
 *  - IDEMPOTENT: re-running makes no change if the marker is already present.
 *  - AUGMENT, NOT BOOTSTRAP: only writes if ~/.claude/CLAUDE.md already exists.
 *    (A fresh machine with no user memory file is left untouched — the postInstall
 *    prints the line to add instead.)
 *  - IN-PLACE: reads + rewrites the SAME path (no tmp+rename), so if the file is a
 *    symlink the link is followed and preserved (the link target is written, the
 *    link itself is never replaced).
 * Returns true if a line was added, false if it was already present or the file
 * does not exist (augment-only).
 */
export function ensureClaudeMdImport(
  config: ResolvedConfig,
  moduleId: string,
  sectionId: string,
): boolean {
  const target = userClaudeMdPath(config);
  if (!fs.existsSync(target)) return false; // augment, don't bootstrap

  const marker = markerComment(moduleId, sectionId);
  const current = fs.readFileSync(target, 'utf-8');
  if (current.includes(marker)) return false; // idempotent

  const importLine = claudeMdImportLine(config, moduleId, sectionId);
  const block = `\n${marker}\n${importLine}\n`;
  fs.writeFileSync(target, current.replace(/\n*$/, '\n') + block);
  return true;
}

/**
 * Remove a module's managed @import line (and its marker) from ~/.claude/CLAUDE.md.
 * Only the marker line and the single line that follows it are removed — the user's
 * own content is never touched. No-op if the file or marker is absent.
 */
export function removeClaudeMdImport(
  config: ResolvedConfig,
  moduleId: string,
  sectionId: string,
): void {
  const target = userClaudeMdPath(config);
  if (!fs.existsSync(target)) return;

  const marker = markerComment(moduleId, sectionId);
  const lines = fs.readFileSync(target, 'utf-8').split('\n');
  const out: string[] = [];
  for (let i = 0; i < lines.length; i++) {
    if (lines[i].trim() === marker) {
      i++; // also skip the @import line that follows the marker
      continue;
    }
    out.push(lines[i]);
  }
  // Collapse the blank line we may have left behind, keep a trailing newline.
  fs.writeFileSync(target, out.join('\n').replace(/\n{3,}/g, '\n\n').replace(/\n*$/, '\n'));
}
