import fs from 'node:fs';
import path from 'node:path';
import type { ResolvedConfig, TmuxConfigPatch } from './types.js';

/**
 * tmux config drop-in writer.
 *
 * The toolkit never edits the user's hand-written, version-controlled tmux.conf.
 * Instead, each module that needs tmux directives gets its own generated drop-in:
 *   ~/.config/tmux/tmux.conf.d/claude-toolkit-<moduleId>.conf
 * sourced by the main config through one stable, path-relative line the user adds
 * once (version-controlled):
 *   source-file -q ~/.config/tmux/tmux.conf.d/*.conf
 *
 * This cleanly separates the two ownerships that otherwise collide in one file:
 *  - the user's tmux.conf stays pure source (no machine-specific absolute paths,
 *    nothing the toolkit rewrites);
 *  - the toolkit owns its drop-in files outright (free to rewrite/delete, no
 *    marker blocks, no in-place edits to back out).
 *
 * tmux applies `set` last-write-wins, and the drop-in is sourced at the end, so a
 * drop-in line can OVERRIDE an earlier main-config setting (e.g. re-set
 * @resurrect-processes without "~claude") without touching the original line.
 *
 * Install = write the drop-in. Uninstall = delete it. Idempotent by construction.
 */

function tmuxDir(config: ResolvedConfig): string {
  return path.join(config.home, '.config', 'tmux');
}

function dropinPath(config: ResolvedConfig, moduleId: string): string {
  return path.join(tmuxDir(config), 'tmux.conf.d', `claude-toolkit-${moduleId}.conf`);
}

/** True if the user has a main tmux.conf (we augment existing configs only). */
function mainConfExists(config: ResolvedConfig): boolean {
  return fs.existsSync(path.join(tmuxDir(config), 'tmux.conf'));
}

/**
 * Write a module's drop-in file. `patch.lines`/`patch.overrides` must already be
 * template-resolved by the caller (InstallProgress, via buildVarMap) — same as
 * hook commands. Overrides are emitted last so they win.
 */
export function applyTmuxConfig(
  config: ResolvedConfig,
  moduleId: string,
  patch: TmuxConfigPatch,
): void {
  // Augment existing configs only — never bootstrap tmux for the user.
  if (!mainConfExists(config)) return;

  const out: string[] = [
    `# Generated by claude-toolkit (module: ${moduleId}). DO NOT EDIT / version.`,
    `# Source of truth: src/modules/${moduleId}/manifest.ts (tmuxConf). Regenerated`,
    `# on every install; deleted on uninstall. Sourced via the *.conf glob the main`,
    `# tmux.conf adds once. Machine-specific (absolute paths) — intentionally not`,
    `# committed; reproduced by re-running the toolkit install on a fresh machine.`,
    '',
  ];
  if (patch.lines.length > 0) {
    out.push(...patch.lines, '');
  }
  if (patch.overrides && patch.overrides.length > 0) {
    out.push(
      '# Overrides: these intentionally shadow settings from the main tmux.conf',
      '# (tmux uses last-write-wins, and this drop-in is sourced last).',
      ...patch.overrides,
      '',
    );
  }

  const target = dropinPath(config, moduleId);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  const tmp = target + '.tmp';
  fs.writeFileSync(tmp, out.join('\n'));
  fs.renameSync(tmp, target);
}

/** Delete a module's drop-in file. */
export function removeTmuxConfig(config: ResolvedConfig, moduleId: string): void {
  const target = dropinPath(config, moduleId);
  if (fs.existsSync(target)) fs.unlinkSync(target);
}
